### PR TITLE
add standardized SED labels to protoDC2 reader

### LINKED ISSUE #67: Make SED labels conform to the schema in protoDC2 reader
Now that we have agreed on how to specified SED labels in the [schema](https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md), we should make SED labels in the protoDC2 reader conform to the schema.

### PR DESCRIPTION
**Pull request by yymao**
This PR adds  standardized SED labels in the protoDC2 reader. This PR fixes #67.

### CODE REVIEW

**Comment by yymao** [comment]
@dkorytov maybe we can use this PR to also add `A_v` and `R_v` as @evevkovacs suggested?  If you want to open a new branch that's fine too, but in that case it's probably better to merge this one first.

**Comment by dkorytov** [comment]
The schema defines the observed magnitudes as lensed. The observed magnitudes in protoDC2 aren't lensed. I don't think it will be that hard to add in magnification...let me talk to Patricia.

**Comment by yymao** [comment]
Indeed..., we could have `mag_true_<band>_<filter>` in the schema.

**Comment by yymao** [comment]
So I think we have a few things to address that we may want to include here, or in a new PR after this one is merged:

- this PR
- Issue #70
- Add lensed observed mag, and/or add `mag_true_<band>_<filter>` in the schema
- Remove unused columns (component-wise ellipticity) in the catalog and schema

**Pull request merged**
