### PR TITLE
First version of instance catalog reader

### PR DESCRIPTION
**Pull request by fjaviersanchez**
Still not 100% finished but I open the PR so you guys can make suggestions on how to modify this. Thanks!

### CODE REVIEW

**Comment by yymao** [comment]
Thanks, @fjaviersanchez. Will take a look. We can also discuss more details next week!

**Comment by slac-srs** [comment]
Can one of the admins verify this patch?

**Comment by yymao** [comment]
Running the DESCQA readiness test on this updated reader:
https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-04-07_26&test=readiness_protoDC2&right=2018-04/2018-04-07_26/readiness_protoDC2/instance_test/SUMMARY.html

Did we mess up disk/bulge sersic indices?

**Comment by yymao** [comment]
The disk/bulge were labelled wrong and now have been fixed. 

A new readiness test run: https://portal.nersc.gov/project/lsst/descqa/v2/?run=2018-04-07_27&test=readiness_protoDC2&right=2018-04/2018-04-07_27/readiness_protoDC2/instance_test/SUMMARY.html

**Comment by fjaviersanchez** [comment]
Wow this is awesome. Thanks @yymao! It looks great to me.

**Pull request merged**
