### PR TITLE
V4.6.1

### PR DESCRIPTION
**Pull request by dkorytov**
Updating the GCR for ProtoDC2 v4.6.1

v4.6.0 doesn't have shears, so it's not an official release to reduce possible confusion.

### CODE REVIEW

**Comment by aphearin** [comment]
@erykoff - this is the reader you need to run redMaPPer on v4.6.1 - it'll be ready for you to use after @yymao merges this

**Comment by yymao** [comment]
Before this is merged, you can still use this reader by doing
```sh
git clone -b v4.6.1 https://github.com/dkorytov/gcr-catalogs.git
```

**Comment by erykoff** [comment]
I cloned this branch, and get the following error: `ValueError: Native quantity `mag_true_Y_lsst` does not exist (required by `mag_true_Y_lsst`)`.
All the other columns that I need appear to be there.

**Comment by dkorytov** [comment]
@erykoff  - mag_true_Y_lsst is relabeled as mag_true_y_lsst. Did mag_true_Y_lsst work before?

**Comment by erykoff** [comment]
Yes, the capital Y worked before, and now lower-case y works.

**Comment by yymao** [comment]
@erykoff that's expected. Sorry for the backward incompatible change.

**Comment by dkorytov** [comment]
@erykoff. Ah, I see the reader automatically converts the upper case band names into lower case--the hdf5 catalog file has 'y' and not 'Y'. We probably should support both upper and lower case 'y' so we don't break old code and people don't need to memorize to capitalize 'y' in the future.

**Comment by yymao** [comment]
Thanks, @dkorytov. I will review this tomorrow.

**Comment by yymao** [comment]
Thanks, @dkorytov. I've tested this PR as well.

**Pull request merged**
