### PR TITLE
add reader and config for protodc2 tidal addon catalog

### PR DESCRIPTION
**Pull request by yymao**
This PR adds a reader and a config file for the protoDC2 tidal addon catalog @EiffL created.

### CODE REVIEW

**Comment by EiffL** [comment]
Yes that will work, sorry I could have done myself but I was initially thinking of modifying the AlphaQ reader to read in an auxilliary file and expose the tidal field along with the other information

**Comment by yymao** [comment]
@EiffL if the arrays have been sorted in the same order as the original catalog, I would modify the original reader too. But in this case, I figure it is better to use `pandas.merge`. Make sense?

**Comment by yymao** [comment]
@EiffL I only exposed `eigvals` and `eigvects` --- are there other fields I should expose?

**Comment by yymao** [comment]
This PR has been tested and can be merged. Here's an example of how to use it and pandas to add the info to the main catalog.

```python
import pandas as pd
import GCRCatalogs

gc = GCRCatalogs.load_catalog('protoDC2')
gc_tidal = GCRCatalogs.load_catalog('protoDC2_addon_tidal')

data = pd.DataFrame(gc.get_quantities(['galaxy_id', 'ra', 'dec'])).set_index('galaxy_id')
data_tidal = pd.DataFrame(gc_tidal.get_quantities(gc_tidal.list_all_quantities())).set_index('galaxy_id').join(data)
```

**Pull request merged**
