### PR TITLE
check md5sum for protoDC2

### LINKED ISSUE #54: implement a version checker for protoDC2 reader
The version checker would check the github repo (if internet available) to ensure that users have the most up-to-date reader installed.

### PR DESCRIPTION
**Pull request by yymao**
This PR adds a md5sum check in the protoDC2 reader so we can make sure the catalog file itself is not modified. 

This PR will fix #54.

### CODE REVIEW

**Comment by dkorytov** [comment]
Whoops, I didn't mean to submit that as the review summary.

**Comment by yymao** [comment]
@dkorytov Yes, we can. Note that once the `md5` field is added in the yaml file, it'll take longer to load the catalog though (hence I created a `protoDC2_test` alias for a catalog without md5 check). 

Anyway, I just gave you push privilege, so you can add the MD5 sum to the yaml files and push to the `protodc2-version-check` branch on `LSSTDESC/gcr-catalogs`.

**Comment by yymao** [comment]
@dkorytov let me know if you approve or have any further comments. I'd like to merge this so that we can use it for Run 1.1. I assume we won't change the catalog file between now and the start of Run 1.1, right? @dkorytov @evevkovacs

**Comment by dkorytov** [comment]
Everything looks good. As far as I understand, everything in the current catalog version looks fine. So there shouldn't be a new version for run1.1.

**Pull request merged**
