### PR TITLE
add version, total ellipticity & position angle to buzzard

### PR DESCRIPTION
**Pull request by yymao**
@j-dr, this PR adds version, position angles, minor-axis sizes, total ellipticities, to the buzzard reader, so that it matches our [updated schema](https://github.com/LSSTDESC/gcr-catalogs/blob/add-schema/GCRCatalogs/SCHEMA.md).  Please take a look and let me know if it looks good. Thanks!

### CODE REVIEW

**Comment by yymao** [comment]
Pinging @j-dr to review this PR.

**Comment by j-dr** [comment]
I don't _major2minor is correct. The sizes in buzzard are the radii enclosing half the light, they don't know anything about the ellipticity. I'll have to think about how to make this work with the current size definitions which use major and minor axes.

**Comment by slac-srs** [comment]
Can one of the admins verify this patch?

**Comment by yymao** [comment]
@j-dr any progress on this?

**Comment by j-dr** [comment]
Unless I'm missing something, I don't think there is a simple way to get a major and minor axis size using the size and ellipticity fields in buzzard. Are there equations describing the conventions used in the schema for ellipticities and sizes somewhere that I can look at?

**Comment by yymao** [comment]
@j-dr the definition we are using is 

`E (total ellipticity) = sqrt(E1^2+E2^2) = (1-q)/(1+q))`, where `q = size_minor/size`

**Comment by yymao** [comment]
Hi @j-dr, I want to check with you to see if you have further thoughts on this, or should I just remove `size_minor` from the reader and then merge this?

**Comment by yymao** [comment]
@j-dr I went ahead to remove `size_minor` in the reader. Is it ok that we merge this?

**Pull request merged**
