### PR TITLE
magnitudes include host dust extinction

### LINKED ISSUE #104: map magnitudes to dusted magnitudes in protoDC2
It is recently discovered that the "dusted" magnitudes in the protoDC2 catalogs are accounting for the dust extinction from the host galaxy, but not from the Milky Way. Hence, these dusted magnitudes are what most general users would want to use. However, currently the magnitudes that are exposed via GCR are the undusted magnitudes, which are mostly only relevant for CatSim. 

Hence, we should map the magnitudes in GCR to dusted magnitudes in protoDC2. 

Thanks to @aphearin @evevkovacs @danielsf @rongpu for raising the clarifying this issue.

### PR DESCRIPTION
**Pull request by dkorytov**
The default magnitudes in the GCR include the dust in the host galaxy. 

I think I fixed the commit history issue. 

fixes #104

### CODE REVIEW

**Comment by rbiswas4** [comment]
Sorry, just checking: Is this for the galaxy itself or point sources (like SN) within the galaxy too?

**Comment by dkorytov** [comment]
This just for ugriz bands (SDSS & LSST) of the galaxy. I think SN are added later in CatSim.

**Comment by rbiswas4** [comment]
Thanks!

**Comment by yymao** [comment]
Looks good to be. Once we reach a conclusion in #104, we can include the fix to SEDs in this PR too.

**Comment by dkorytov** [comment]
It all looks good. :)

**Pull request merged**
