### PR TITLE
Prepare release on PyPI

### PR DESCRIPTION
**Pull request by yymao**
This PR adds a github action and updates setup.py in preparation for releasing gcr-catalogs on pypi.

### CODE REVIEW

**Review by eacharles — APPROVED** [review]
Thanks Yao, this looks great!

**Comment by yymao** [comment]
Thanks!  Plan to merge around 2p PDT in case others want to take a look.

**Comment by evevkovacs** [comment]
I have a PR to merge the new roman-rubin catalog readers that's almost ready to go.  Should we try to get this in the release?

**Comment by yymao** [comment]
That's fine by me.  I don't know if @eacharles has a tight time frame on things that depend on this release though.

**Comment by eacharles** [comment]
For this PR, I don’t, but it would be nice to at least have a placeholder release on pypi in the next day or so so that we can get the new verision of `rail_astro_tools` up as well..   But of course you can just load what with twine by hand.

-e

**Comment by evevkovacs** [comment]
It appears that we have some issues still with the catalog so please go ahead as planned without my PR.  Thanks

**Pull request merged**
