### PR TITLE
fix a mismatch of size_minor in quantity translation

### PR DESCRIPTION
**Pull request by yymao**
@jchiang87 you can use this PR to try again.

### CODE REVIEW

**Comment by jchiang87** [comment]
The galaxy major/minor axis entries in the resulting instance catalogs look ok now.  I'm running a quick test image with imsim as an additional sanity check.

**Comment by jchiang87** [comment]
fwiw, here is the imsim output for the center of the central sensor in the LSST focal plane using an instance catalog created with this fix:
gcr_catalogs_fix_450581
cf. https://github.com/LSSTDESC/DC2_Repo/issues/69#issuecomment-353762198

**Comment by yymao** [comment]
Thanks @jchiang87. Does it mean now #56 is considered fixed?

**Comment by jchiang87** [comment]
I think so.

**Pull request merged**
