### PR TITLE
Add 2.1i (v1) object catalog configs

### LINKED ISSUE #319: create an entry for 2.1i object catalog
Cf. https://github.com/LSSTDESC/DC2-production/issues/347 -- once the files are copied to NERSC, we need to create an entry for the 2.1i object catalog, and check that the reader works as expect.

### PR DESCRIPTION
**Pull request by yymao**
This PR adds entries for the 2.1i (v1) DPDD object catalogs, and also aliases that do not have "v1" in their catalog names.

There are still a few things about the underlying data that block this PR: 

- [x] The catalog files have not been moved to the final destination yet.
- [x] The trimmed HDF5 files still need to be generated. 
- [x] The schema yaml files still need to be generated. 

This PR fixes #319.

### CODE REVIEW

**Comment by yymao** [comment]
I also wonder if we should continue to provide both the full and trimmed versions considering that our space on `projecta` seems to be very tight?

**Comment by yymao** [comment]
Another question: should we attempt to include this in our v0.11.0 release?

**Comment by wmwv** [comment]
We should not include #320.
My understanding of https://github.com/LSSTDESC/DC2-production/issues/347 is that the first Run 2.1i 6-month processing run revealed some problems still being diagnosed.

**Comment by yymao** [comment]
After an offline chat with Michael, we decide to ask the DM-DC2 TF during their Monday telecon.

**Comment by yymao** [comment]
@wmwv A few minor things to decide:

Right now we have `dc2_object_run2.1i` as an alias of `dc2_object_run2.1i_v1`. We are going to change `dc2_object_run2.1i_v1` to `dc2_object_run2.1i_6m_v1`. Do we want to 
1. rename `dc2_object_run2.1i` to `dc2_object_run2.1i_6m`, OR
2. add `dc2_object_run2.1i_6m`, and for now both `dc2_object_run2.1i` and `dc2_object_run2.1i_6m` point to `dc2_object_run2.1i_6m_v1`?

Another question is whether we'll continue to provide the trimmed version. And if so, can you run the script (or specifically assign someone to run the script)?

**Comment by yymao** [comment]
Final naming scheme will follow the conclusion of this discussion: https://github.com/LSSTDESC/ImageProcessingPipelines/issues/93#issuecomment-500538293

**Comment by EiffL** [comment]
Quick question, what's the timeline for this? So that I can make the corresponding metacal catalog

**Comment by yymao** [comment]
We are aiming to merge this (pending name fixes) and then tag and release tomorrow. 

But this PR should be working now, so @EiffL, I think you can use it to create metacal add-ons if you want to do it now.

**Comment by wmwv** [comment]
Trim catalogs produced and copied to:
`/global/projecta/projectdirs/lsst/production/DC2_ImSim/Run2.1i/dpdd/calexp-v1\:coadd-v1/object_table_summary`
The untrimmed catalogs are 402 GB.  The trimmed catalogs are 18 GB.

**Comment by wmwv** [comment]
`trim_schema.yaml` file produced and copied to the above directory.

`blendedness` is broken.  `base_Blendedness_abs_instFlux` is no longer the name.  It should be `base_Blendeness_abs`.  See https://github.com/LSSTDESC/gcr-catalogs/issues/262.

**Comment by yymao** [comment]
@wmwv should this change be controlled by `dm_schema_version` in https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/dc2_object.py#L307?

**Comment by wmwv** [comment]
PR submitted to fix blendedness
https://github.com/LSSTDESC/gcr-catalogs/pull/324
Trim catalogs being re-generated now at NERSC.  It should take about an hour.

**Comment by wmwv** [comment]
Run 2.1i dr1a v1 trim catalogs and `trim_schema.yaml` updated at NERSC.

**Comment by yymao** [comment]
Thanks, @wmwv, can you review this PR?

**Pull request merged**
