### PR TITLE
update reference catalog reader

### PR DESCRIPTION
**Pull request by yymao**
This PR updates the reference catalog reader to add some quantities that are defined in the schema.

### CODE REVIEW

**Comment by fjaviersanchez** [comment]
@yymao I think that as long as all columns are listed in `list_all_quantities()` it should be fine. One useful quantity for some analysis is going to be `isresolved` (and maybe `isagn`), as long that this one is visible somehow and in the schema, there's no reason to add more modifiers.

**Comment by yymao** [comment]
Question for @fjaviersanchez: should `mag_u_lsst` mapped to `lsst_u` or to `lsst_u_smeared`?

**Comment by fjaviersanchez** [comment]
Honestly, I don't really know. If I understood correctly @danielsf's comment this morning, `lsst_u_smeared` is passed to the DM stack to calibrate the magnitudes/compute the zeropoints, so I guess this should be the one that we have to compare against? But I don't think it is going to make a big difference. @danielsf or @jchiang87 please, correct me if this is wrong.

**Comment by danielsf** [comment]
The various `*_smeared` quantities have Gaussian noise applied to them to simulate that an actual reference catalog (which will be derived from another survey) won't perfectly measure the physical truth.

If we want people to use the reference catalog reader to access the reference catalog in the way it was intended to be used (i.e. as a stand in for data from another survey), then yes, I think the `*_smeared` quantities should be the ones that are aliased to the defaults.

**Comment by yymao** [comment]
@danielsf, thanks! That answers my question. I think we want the ones with `_smeared` to be mapped to the "default" quantities. I've just updated it.

**Comment by yymao** [comment]
Will merge this on Monday unless there's objection.

**Pull request merged**
