### PR TITLE
Bump version to v1.5.0

### PR DESCRIPTION
**Pull request by yymao**
We have enough updates and also some new catalogs that we should make a new release. Note that #607 is not entirely backward compatible, and we should write a warning sentence in the release note and probably on the data portal as well. 

@evevkovacs or @JoanneBogart, would you be able to help write that warning sentence?

### CODE REVIEW

**Comment by evevkovacs** [comment]
Please feel free to edit the above sentences.

**Comment by JoanneBogart** [comment]
LGTM!  Thanks @evevkovacs

**Comment by yymao** [comment]
Thanks @evevkovacs. @JoanneBogart can you give this PR a quick approval?

**Review by JoanneBogart — APPROVED** [review]
Looks fine.

**Pull request merged**
