### PR TITLE
photo-z calibration catalog reader

### PR DESCRIPTION
**Pull request by yymao**
photo-z calibration catalog reader provided by @morriscb

### CODE REVIEW

**Comment by yymao** [comment]
- [ ] need to add a composite yaml file

**Comment by yymao** [comment]
Functional checks for this PR are all completed.

**Comment by yymao** [comment]
This is now ready for review. @morriscb, I've assigned you as a reviewer but maybe you would like to suggest someone else?

**Comment by morriscb** [comment]
Seems to be against the idea of a review for one of the authors to review. Perhaps @sschmidt23 another person from PZ could do it.

**Comment by yymao** [comment]
Thanks @sschmidt23, I've addressed your comment. @morriscb I'm merging this.

**Pull request merged**
