### PR TITLE
Issues/295 - Add DIA Source Run 1.2p test catalog to README

### LINKED ISSUE #295: Add new catalogs in README
@wmwv @EiffL can you put the newly added catalogs into README? Thanks!

### PR DESCRIPTION
**Pull request by wmwv**
@yymao I added the Run 1.2p test catalog to README.

[edited by @yymao: fix #295]

### CODE REVIEW

**Comment by yymao** [comment]
Hmmm, @wmwv it seems that the DIA reader is now missing from this PR?

**Comment by wmwv** [comment]
Maybe I'm just bad at things today.  Give me a bit.

**Comment by wmwv** [comment]
Ah, yes, the previous version of this PR also added a DIA Object reader.  That was an error.  On the DIA Source reader is ready to go.

This PR is now just a 8-line change in the README.md.

**Comment by yymao** [comment]
@wmwv ah ok. So this one is good (and I am merging it now), and it fixes #295. But why is #293 still open?

**Comment by wmwv** [comment]
#293 is still open because the actual DIA Object table hasn't been created or tested.So sure, what I wrote there I think iscorrect, but I haven't actually ever used that to read a catalog.

**Comment by yymao** [comment]
I now understand --- #293 is about DIA object reader, which was not supposed to be included in this PR.

**Pull request merged**
