### PR TITLE
add 1.2p object catalog

### PR DESCRIPTION
**Pull request by yymao**
This PR adds the 1.2p object catalog. Currently the `base_dir` path is temporary and we should move the catalog files to a more central place before this PR is reviewed and merged. I will assign a reviewer after the new location is reflected in the config files. 

For now, this PR allows developers to validate the generation of 1.2p object catalog (cc @wmwv @plaszczy).

### CODE REVIEW

**Comment by yymao** [comment]
I've done some basic validations on this 1.2p object catalog using this PR. In particular, I checked that the tutorial notebooks work with this 1.2p object catalog, and that the values stored in this catalog are consistent with what butler returns. 

Hence, I think this PR is ready for review. At the same time, we should move the catalog files to `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/object_catalog` (cc @heather999 @plaszczy).

**Comment by yymao** [comment]
@heather999 can you help with moving/copying the data files? I believe this would involve running the following lines:

```bash
mkdir /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/object_catalog
cd /global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/object_catalog
cp /global/cscratch1/sd/plaszczy/Run1.2p/run5/*merged_tract_*.hdf5 ./
cp /global/cscratch1/sd/plaszczy/Run1.2p/run5/*schema.yaml ./
chmod g+r *merged_tract_*.hdf5 *schema.yaml
```

**Comment by yymao** [comment]
`base_dir` has now been updated to `/global/projecta/projectdirs/lsst/global/in2p3/Run1.2p/object_catalog`. 

However, the `merged_tract_*.hdf5` files were accidentally deleted and @plaszczy is regenerating them now. Once that's done, I'll ask @heather999 to copy them to the new location again. 

In the meantime, @wmwv, it would be great if you can reapprove, thanks!

**Comment by plaszczy** [comment]
tested and is OK

**Comment by yymao** [comment]
Catalog files have been copied and I have tested to make sure they works. I'm merging this now. Thanks @plaszczy @heather999 for the help.

**Pull request merged**
