### PR TITLE
Issues/274 Reader for DC2 Source Table

### PR DESCRIPTION
**Pull request by wmwv**
Reader for DC2 Source Table.
Currently Run 1.2i exists and has been installed at NERSC.

Based on reading individual Parquet files, one per visit.  1995 files total 25 GB.

Future performance will likely have to be explored.

### CODE REVIEW

**Comment by yymao** [comment]
@wmwv thanks for the PR. I am traveling this week but also want to take a closer look at the reader code, so I may not be able to submit my review until early next week.

**Comment by wmwv** [comment]
Note that this also add requirement for `pyarrow`.  I use `pyarrow.parquet.ParquetFile` to provide file handles.

**Comment by yymao** [comment]
@wmwv can you rebase onto or merge with master and also add `pyarrow` to [`setup.py`](https://github.com/LSSTDESC/gcr-catalogs/blob/master/setup.py#L41) so that travis-ci can run? Thanks!

**Comment by wmwv** [comment]
1. I had to put `pyarrow` in the `install_requires` list in `setup.py`.  Including it in the `extras_requires` list wasn't sufficient for the install to be picked up in the Travis.

2. The `pyarrow` that Travis picks up appears to be inconsistent with the `numpy` that Travis uses.
```
  File "/home/travis/build/LSSTDESC/gcr-catalogs/GCRCatalogs/dc2_source.py", line 11, in <module>
    import pyarrow.parquet as pq
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/pyarrow/__init__.py", line 54, in <module>
    from pyarrow.lib import cpu_count, set_cpu_count
  File "pyarrow/lib.pyx", line 36, in init pyarrow.lib
ImportError: numpy.core.multiarray failed to import
```

**Comment by yymao** [comment]
@wmwv I fixed travis test, but still haven't got time to review the code yet.

**Pull request merged**
