### PR TITLE
Add dc2_object_run2.2i_dr6_v2pre

### LINKED ISSUE #534: Add Run2.2i-dr6-v2pre for validation
See https://github.com/LSSTDESC/DC2-production/issues/414

### PR DESCRIPTION
**Pull request by yymao**
This PR adds the catalog config for `dc2_object_run2.2i_dr6_v2pre` and resolves #534.

### CODE REVIEW

**Review by heather999 — APPROVED** [review]
LGTM - the path looks correct and all the files are now in place.

**Comment by heather999** [comment]
LGTM - do we need to handle the updated metacal too?  I don't know that anyone will look for validation.. but it is available.

**Review by heather999 — APPROVED** [review]
Looks good - thanks!

**Comment by yymao** [comment]
Thanks @heather999. Will merge when the CI tests pass.

**Pull request merged**
