### PR TITLE
Config files for new catalogs

### PR DESCRIPTION
**Pull request by evevkovacs**
Here are the configuration files for the catalog used for the roman-desc simulations  (v_1.1.2) and a newer variant with improved model parameters tuned against Cosmos2020 data.
These catalogs are in the shared catalogs area and the configuration files have been tested with DESCQA. See [ dn/dmag test](https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2024-01-19)

### CODE REVIEW

**Review by yymao — CHANGES_REQUESTED** [review]
Thanks @evevkovacs. If `roman_rubin_v1.1.1_elais` is deprecated (as indicated by README), can you add the `deprecated` tag to its config file?

**Comment by evevkovacs** [comment]
@yymao I added the deprecated tag as requested and updated the information in the skysim_v3.1* yaml files to point to the newer roman_rubin catalog.

**Review by yymao — APPROVED** [review]
Thanks!

**Comment by JoanneBogart** [comment]
Is it ok to merge, now that it's approved?

**Pull request merged**
