### PR TITLE
Proposing v1.0.0 release

### PR DESCRIPTION
**Pull request by yymao**
I am proposing the v0.20.0 release. We don't have any open PR at this moment, so if no one objects (and one approves), I'll merge this and create a tag tomorrow.

### CODE REVIEW

**Comment by katrinheitmann** [comment]
How about a v1.0 release? :-) My understanding is that this work is now mature enough to get the 1.0 stamp of approval tag. Thanks for all the hard work on this!

**Comment by heather999** [comment]
Happy to see a release and call it whatever :) v1.0.0 sounds fine.

**Review by heather999 — DISMISSED** [review]
I'll pre-approve and we can hash out what the tag is.  Once a release is made, I'll get desc-python and desc-stack updated.

**Review by wmwv — APPROVED** [review]
LGTM

**Comment by yymao** [comment]
I've now fixed the linter issue and bump the version to 1.0.0. Will merge in a few hours.

**Review by heather999 — APPROVED** [review]
LGTM

**Pull request merged**
