### PR TITLE
really deprecate this time

### PR DESCRIPTION
**Pull request by JoanneBogart**
This change was intended to be part of the previous PR

### CODE REVIEW

**Comment by yymao** [comment]
Thanks @JoanneBogart -- should we just use this PR to deprecate other truth catalogs that we plan to deprecate? Seems a bit strange to just deprecate this one. 

We should also edit the README to point to the new set of truth catalogs.

**Comment by JoanneBogart** [comment]
@yymao Yes, it would be fine to deprecate whatever else needs deprecating.  Do you have a list?

**Comment by yymao** [comment]
These can be deprecated now:
- dc2_truth_run2.2i_sn_truth_summary.yaml
- dc2_truth_run2.2i_sn_variability_truth.yaml
- dc2_truth_run2.2i_star_lc_stats.yaml
- dc2_truth_run2.2i_star_truth_summary.yaml
- dc2_truth_run2.2i_star_variability_truth.yaml

This should be deprecated when the new galaxy truth table is made:
- dc2_truth_run2.2i_galaxy_truth_summary.yaml

This should be deprecated when the new tract-partitioned merged truth table is made:
- dc2_truth_run2.2i_summary_tract_partition.yaml

**Comment by JoanneBogart** [comment]
The SN and star ones are taken care of.  I could deal with the galaxies or, since that involves adding new files as well as deprecating, that could be in a separate PR.

**Comment by yymao** [comment]
Thank you @JoanneBogart!  We can move galaxy truth, raw truth, and truth match in other PRs indeed.

Can you update the listing in the README file in this PR as well?

**Comment by JoanneBogart** [comment]
I went ahead and added configs for galaxies in this PR.  I also changed portal directory name from `truth_variable` to `truth_unmerged` (maybe `truth_raw` would be better?) because it will include the galaxy truth.  README.md informatio is updated for all the new catalogs to date (everything but truth match).  I'm not sure what to do about the file SCHEMA.md, in particular the subsection "Quantities belonging to all truth summary catalogs".  Preferably, we either go into detail in the package documentation or in the Release Note, but not both.

**Review by yymao — APPROVED** [review]
Thanks @JoanneBogart. Looks good to me.  Approving this now. 

I just realize we also need to update the schema, but we can open another PR
https://github.com/LSSTDESC/gcr-catalogs/blob/master/GCRCatalogs/SCHEMA.md

**Pull request merged**
