### PR TITLE
add in Run2.2i DR2 object and metacal

### LINKED ISSUE #510: add Run2.2i dr2
Now that the CC processing seems complete - it's time to add some entries for the Run2.2i DR2 object catalogs and metacal.

### PR DESCRIPTION
**Pull request by heather999**
fix #510 
Added in the files I think are necessary to point to the Run2.2i DR2 v1 object catalogs and metacal.  Also updated the tract listing this time :)

### CODE REVIEW

**Review by yymao — CHANGES_REQUESTED** [review]
Thanks, @heather999. Can you also add `dc2_object_run2.2i_dr2` to the README?

I am validating the metacal add-on. There are a few missing tracts in metacal (4226, 2723, 2724, 4229, 2725, 2726, 2727, 2728, 2729, 2730, 2731, 2732, 2733, 2734, 4035, 4857). 

Also among many of the tracts that are available, the number of entries in metacal do not match those in the object catalogs, suggesting failing patches. (cc @johannct)

Hence `dc2_object_run2.2i_dr2_v1_with_metacal` and `dc2_object_run2.2i_dr2_with_metacal` will not work in their current form and should be removed for now. 

For validation purpose, we can create an metacal only entry for temporary use.  

```yaml
subclass_name: dc2_metacal.DC2MetacalCatalog
base_dir: ^/DC2-prod/Run2.2i/dpdd/Run2.2i-dr2-v1/metacal_table_summary
bands: 'griz'
apply_metacal_test3_fix: true
```

**Comment by yymao** [comment]
@johannct -- here's a list of possible missing patches in each metacal tract when compared to the object catalog for DR2.

```
2896 0,0; 0,6; 1,0; 1,1; 1,2; 1,3
2897 0,0; 1,0; 2,0; 3,0; 4,0; 5,0; 6,0
2898 0,0; 1,0; 2,0; 3,0; 4,0; 5,0; 6,0
2899 1,0; 1,1; 3,1; 5,2
2900 1,3; 2,5; 3,4; 6,6
2901 0,5; 1,6; 2,1; 2,4; 3,1; 4,2
2902 0,0; 1,0; 2,0; 3,0; 4,0; 5,0; 6,0
2903 0,0; 1,0; 2,0; 3,0; 4,0; 5,0; 6,0
2904 0,0; 1,0; 2,0; 3,0; 4,0; 5,0; 6,0
2905 0,0; 1,0; 2,0; 3,0; 4,0; 5,0; 6,0
2906 0,0; 1,0; 2,0; 3,0; 4,0; 5,0; 6,0
2907 Missing more than 39 patches
2908 2,2; 3,3; 5,2; 5,3; 5,4
3074 3,2
3086 2,1; 2,4; 3,1; 6,0
3256 5,0; 5,1; 5,2
3268 4,0; 4,1; 4,2; 4,3; 4,4; 6,2; 6,6
3441 0,2; 0,3; 0,4
3443 1,2
3445 6,6
3453 0,4; 0,5; 1,2; 6,4
3454 6,0; 6,2
3631 2,5; 2,6
3633 4,2
3636 3,4
3643 2,5; 3,6; 4,0; 6,4
3825 4,2; 4,5; 4,6
3829 6,0
3830 3,3
3832 1,1
3837 4,1; 4,2; 4,3; 4,6; 5,6
4022 0,0; 0,2
4034 1,4; 4,4; 5,5
4224 2,0; 3,0; 3,3; 3,4; 3,5
4225 0,6
4227 1,1
4232 2,2
4236 2,0; 3,0; 3,3; 3,4; 3,6
4429 6,1; 6,4; 6,5; 6,6
4437 Missing more than 40 patches
4438 Missing more than 41 patches
4439 4,1
4440 0,5; 0,6
4441 6,0; 6,5; 6,6
4636 2,0; 2,1
4644 Missing more than 17 patches
4645 4,3
4648 2,5; 3,0; 5,1
4848 5,1; 5,2; 5,3
4851 3,0
4854 4,2
4860 4,1; 4,2; 5,1; 5,4; 6,0
5062 1,4
5063 0,6; 1,6; 2,6; 3,6; 4,6; 5,6; 6,6
5064 2,6; 3,6; 4,6; 5,6
5065 0,6; 1,6; 3,6; 5,6; 6,6
5066 0,6; 1,5; 1,6; 2,6; 3,6; 4,6; 5,6; 6,6
5067 1,6; 2,6; 3,6; 4,6; 5,6; 6,6
5068 Missing more than 33 patches
5069 0,6; 1,6; 2,6; 3,6; 4,6; 5,6
5070 0,4; 0,6; 3,3; 5,6
5071 0,6; 1,6; 2,6; 3,6; 4,6; 5,6; 6,6
5072 0,6; 2,6; 3,6; 4,6; 5,6
5073 3,6; 5,4
5074 1,3; 1,5; 2,5; 4,5; 5,6; 6,6
```

**Comment by yymao** [comment]
@heather999 thanks for the update. Do you want to remove the `dc2_object_run2.2i_dr2_v1_with_metacal` and `dc2_object_run2.2i_dr2_with_metacal` config files and get the rest merged first, or wait until we sort out the missing patch issue?

**Comment by heather999** [comment]
I'll update this tomorrow - but yea, I don't think we'll get metacal sorted out quickly enough, and we'd like to make the object catalogs more generally available.

**Review by yymao — APPROVED** [review]
Thanks, @heather999

**Pull request merged**
