### PR TITLE
Prepare v0.11.0 release

### PR DESCRIPTION
**Pull request by yymao**
Let's prepare the v0.11.0 release. This release updates the minor version because fixing some units in protoDC2/cosmoDC2 means the update is not entirely backward compatible for end users. The new base class `DC2DMCatalog` is also a significant dev-facing update. 

Issues/PRs to close for this release:
- [x] #294 
- [x] #295
- [x] #299 
- [x] #301 
- [x] #302
- [x] #303

### CODE REVIEW

**Comment by yymao** [comment]
In particular, should we wait for #293, @wmwv?

**Comment by wmwv** [comment]
Yes, we should wait for #293.

**Comment by yymao** [comment]
@wmwv what's the ETA of #293? Should we tag this by Tuesday or a set date (as discussed in today's DATF telecon)?

**Comment by wmwv** [comment]
Sorry for not responding about #293.  In principle, given the time delay, sure we don't need to do #293 first.

Unfortunately, I just discovered #302.  We definitely need to fix that before closing this present PR.

**Comment by yymao** [comment]
@wmwv I'd like to tag the master with v0.11.0 and make a release. Have you recently tested the master?

**Comment by yymao** [comment]
turns out I found two bugs. fixing them now.

**Comment by yymao** [comment]
Await the following PRs to be merged
- [ ] #308 
- [x] #309 
- [ ] #310

**Comment by yymao** [comment]
Also should wait for
- [ ] #311 
- [ ] #312 
- [ ] #313 
- [ ] #314

**Comment by yymao** [comment]
@wmwv I think this is now ready to be merged and tagged. My remaining question is whether we'd like to include #320 (2.1i object catalog). Thoughts?

**Comment by wmwv** [comment]
Don't include #320.  Tag and release `v0.11.0` as is.

**Comment by yymao** [comment]
I'm merging this now, but will hold off on making a release until Monday.

**Pull request merged**
